import { useEffect, useMemo, useState } from 'react';
import { useAuth } from '@/lib/AuthContext';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { BookOpen, Users, ArrowRight, Sparkles, Target, BriefcaseBusiness } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { CommunityGroup, Job } from '@/lib/careerData';
import { dashboardMetrics } from '@/lib/profileMatching';

export default function DashboardPage(){
 const {user}=useAuth(); const [jobs,setJobs]=useState<Job[]>([]); const [groups,setGroups]=useState<CommunityGroup[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{Promise.all([fetch('/api/jobs').then(r=>r.json()),fetch('/api/community/groups').then(r=>r.json())]).then(([j,g])=>{setJobs(j);setGroups(g)}).catch(console.error).finally(()=>setLoading(false))},[]);
 const profile=user?.profileData||{};
 const metrics=useMemo(()=>dashboardMetrics(jobs,groups,profile),[jobs,groups,profile]);
 const firstName=user?.name?.trim().split(/\s+/)[0]||'there';
 return <div className="space-y-8">
  <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4"><div><h1 className="text-3xl font-bold tracking-tight">Welcome back, {firstName}</h1><p className="text-slate-500">This dashboard is generated from the account you signed in with.</p></div><div className="flex gap-2"><Button asChild variant="outline"><Link to="/profile">Edit Profile</Link></Button><Button asChild className="bg-blue-600 text-white"><Link to="/jobs">Find Jobs</Link></Button></div></div>
  <Card className="border-blue-100 bg-blue-50/50 dark:bg-blue-950/20"><CardContent className="p-5 flex gap-3"><Sparkles className="h-5 w-5 text-blue-600 mt-1"/><div><p className="font-semibold">{profile.currentTitle||'Current role not set'} → {profile.targetCareer||'Target role not set'}</p><p className="text-sm text-slate-600 dark:text-slate-300">Change this account's profile or resume and the dashboard, jobs, learning and community recommendations recalculate.</p></div></CardContent></Card>
  {loading?<p>Loading your personalized dashboard…</p>:<>
  <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
   <Card><CardHeader><CardTitle className="text-sm">Profile completion</CardTitle></CardHeader><CardContent><div className="text-2xl font-bold">{metrics.completion}%</div><Progress value={metrics.completion} className="mt-2 h-2"/><p className="text-xs text-slate-500 mt-2">Based only on this signed-in user's profile.</p></CardContent></Card>
   <Card><CardHeader><CardTitle className="text-sm">Target-role readiness</CardTitle></CardHeader><CardContent><div className="text-2xl font-bold">{metrics.readiness}%</div><Progress value={metrics.readiness} className="mt-2 h-2"/><p className="text-xs text-slate-500 mt-2">Calculated from this user's skills and matching jobs.</p></CardContent></Card>
   <Card><CardHeader><CardTitle className="text-sm">AI change concern</CardTitle></CardHeader><CardContent><div className="text-2xl font-bold">{metrics.exposure}%</div><p className="text-xs text-slate-500 mt-2">From this account's own response.</p><Button variant="link" className="px-0 h-auto text-xs" asChild><Link to="/ai-impact">Explore AI impact <ArrowRight className="h-3 w-3 ml-1"/></Link></Button></CardContent></Card>
   <Card><CardHeader><CardTitle className="text-sm">Relevant communities</CardTitle></CardHeader><CardContent><div className="text-2xl font-bold">{metrics.relevantGroups}</div><p className="text-xs text-slate-500 mt-2">Groups matching this user's role, target, skills or interests.</p></CardContent></Card>
  </div>
  <div className="grid gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle>Personalized readiness trend</CardTitle><CardDescription>Derived from your current profile completeness and target-role readiness.</CardDescription></CardHeader><CardContent><div className="grid grid-cols-4 gap-3 items-end h-48">{metrics.trend.map((value,index)=><div key={index} className="flex flex-col items-center gap-2 h-full justify-end"><div className="w-full max-w-24 rounded-t-md bg-blue-600/80" style={{height:`${Math.max(6,value)}%`}} title={`${value}%`}/><span className="text-xs text-slate-500">Stage {index+1}</span><span className="text-xs font-medium">{value}%</span></div>)}</div></CardContent></Card>
  <Card><CardHeader><CardTitle>Skill gaps & learning</CardTitle><CardDescription>{profile.targetCareer?`Priorities for ${profile.targetCareer}`:'Set a target role to personalize this section.'}</CardDescription></CardHeader><CardContent><div className="flex flex-wrap gap-2 mb-5">{metrics.gaps.length?metrics.gaps.map(skill=><Badge key={skill} variant="destructive">{skill}</Badge>):<span className="text-sm text-slate-500">No priority gaps detected yet.</span>}</div><Button asChild variant="outline" className="w-full"><Link to="/learning"><BookOpen className="h-4 w-4 mr-2"/>Open personalized learning</Link></Button></CardContent></Card></div>
  <div><div className="flex items-center justify-between mb-3"><h2 className="text-lg font-semibold">Best-fit opportunities for this account</h2><Button variant="link" asChild><Link to="/jobs">View all</Link></Button></div><div className="grid gap-4 md:grid-cols-3">{metrics.topJobs.map(job=><Card key={job.id}><CardHeader><div className="flex justify-between gap-2"><CardTitle className="text-base">{job.title}</CardTitle><Badge variant={job.match>=70?'success':job.match>=45?'warning':'secondary'}>{job.match}%</Badge></div><CardDescription>{job.company}</CardDescription></CardHeader><CardContent><div className="flex flex-wrap gap-2">{job.requiredSkills.slice(0,4).map(s=><Badge key={s} variant="outline">{s}</Badge>)}</div><Button variant="link" className="px-0 mt-3" asChild><Link to={`/job-fit/${job.id}`}>Analyze fit <ArrowRight className="h-3 w-3 ml-1"/></Link></Button></CardContent></Card>)}{!metrics.topJobs.length&&<Card className="md:col-span-3"><CardContent className="p-8 text-center text-slate-500">Add your current role, target role and skills to generate job matches.</CardContent></Card>}</div></div>
  <div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle>Next best action</CardTitle><CardDescription>Based on this account's current skill gaps</CardDescription></CardHeader><CardContent><div className="flex items-center gap-3"><Target className="h-5 w-5 text-purple-600"/><div><p className="font-medium">{metrics.gaps[0]?`Build ${metrics.gaps[0]}`:'Complete your career profile'}</p><p className="text-sm text-slate-500">Your next action changes as your target role and skills change.</p></div><Button variant="outline" asChild className="ml-auto"><Link to={metrics.gaps[0]?'/learning':'/profile'}>{metrics.gaps[0]?'Learn':'Complete'}</Link></Button></div></CardContent></Card><Card><CardHeader><CardTitle>Build your network</CardTitle></CardHeader><CardContent><div className="flex items-center gap-3"><Users className="h-5 w-5 text-green-600"/><div><p className="font-medium">{metrics.relevantGroups?`Explore ${metrics.relevantGroups} relevant communities`:'Add interests to find communities'}</p></div><Button variant="outline" asChild className="ml-auto"><Link to="/community"><BriefcaseBusiness className="h-4 w-4 mr-2"/>Explore</Link></Button></div></CardContent></Card></div>
  </>}
 </div>
}
