import { useEffect, useRef, useState } from 'react';
import { useAuth } from '@/lib/AuthContext';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Upload, Save, FileText, LogOut } from 'lucide-react';

const asText=(values:string[]|undefined)=>values?.join(', ')||'';
export default function ProfilePage(){
 const {user,updateProfile,logout}=useAuth(); const [form,setForm]=useState<any>({}); const [saved,setSaved]=useState(false); const ref=useRef<HTMLInputElement>(null);
 useEffect(()=>{const p=user?.profileData||{};setForm({...p,skills:asText(p.skills),interests:asText(p.interests)})},[user?.id,user?.profileData]);
 const set=(k:string,v:any)=>setForm((f:any)=>({...f,[k]:v}));
 const save=()=>{updateProfile({name:form.name || user?.name,yearsExperience:Number(form.yearsExperience||0),skills:String(form.skills||'').split(',').map((x:string)=>x.trim()).filter(Boolean),interests:String(form.interests||'').split(',').map((x:string)=>x.trim()).filter(Boolean)});setSaved(true);setTimeout(()=>setSaved(false),1800)};
 const upload=async(file:File)=>{let text=''; if(file.type==='text/plain'||file.name.toLowerCase().endsWith('.txt')) text=await file.text(); setForm((f:any)=>({...f,resumeName:file.name,resumeText:text}));};
 return <div className="space-y-6 max-w-5xl mx-auto"><div className="flex flex-col md:flex-row justify-between gap-4"><div><h1 className="text-3xl font-bold tracking-tight">Profile & Career Preferences</h1><p className="text-slate-500">This signed-in account is the source for your jobs, learning, community and AI recommendations.</p></div><div className="flex gap-2"><Button onClick={save} className="bg-blue-600 text-white"><Save className="h-4 w-4 mr-2"/>{saved?'Saved':'Save changes'}</Button><Button variant="outline" onClick={logout}><LogOut className="h-4 w-4 mr-2"/>Log out</Button></div></div>
 <div className="grid gap-6 md:grid-cols-3"><div className="md:col-span-2 space-y-6"><Card><CardHeader><CardTitle>Personal information</CardTitle><CardDescription>These details belong only to the currently signed-in account.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><div><Label>Name</Label><Input className="mt-2" value={user?.name||''} onChange={e=>setForm((f:any)=>({...f,name:e.target.value}))}/></div><div><Label>Email / account ID</Label><Input className="mt-2" type="email" value={user?.email||''} readOnly/></div></CardContent></Card>
 <Card><CardHeader><CardTitle>Career profile</CardTitle><CardDescription>Changing the current or target role changes the meaning of your recommendations.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-4 md:grid-cols-2"><div><Label>Current / previous role</Label><Input className="mt-2" value={form.currentTitle||''} onChange={e=>set('currentTitle',e.target.value)} placeholder="e.g. Accountant"/></div><div><Label>Target role</Label><Input className="mt-2" value={form.targetCareer||''} onChange={e=>set('targetCareer',e.target.value)} placeholder="e.g. Data Analyst"/></div></div><div><Label>Years of experience</Label><Input className="mt-2" type="number" min="0" value={form.yearsExperience??''} onChange={e=>set('yearsExperience',e.target.value)}/></div><div><Label>Skills</Label><Input className="mt-2" value={form.skills||''} onChange={e=>set('skills',e.target.value)} placeholder="Excel, SQL, Java, communication"/></div><div><Label>Interests</Label><Input className="mt-2" value={form.interests||''} onChange={e=>set('interests',e.target.value)} placeholder="AI, analytics, product"/></div><div><Label>AI change concern: {form.aiConcern||3}/5</Label><input className="w-full mt-3" type="range" min="1" max="5" value={form.aiConcern||3} onChange={e=>set('aiConcern',Number(e.target.value))}/></div></CardContent></Card>
 <Card><CardHeader><CardTitle>Resume</CardTitle><CardDescription>Replace your resume when your experience or target role changes. Resume text is used as an additional matching signal.</CardDescription></CardHeader><CardContent className="space-y-4"><input ref={ref} type="file" accept=".pdf,.doc,.docx,.txt" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/><Button variant="outline" onClick={()=>ref.current?.click()}><Upload className="h-4 w-4 mr-2"/>Add / replace resume</Button>{form.resumeName&&<div className="flex items-center gap-3 p-3 border rounded-lg"><FileText className="h-5 w-5 text-blue-600"/><div><p className="font-medium">{form.resumeName}</p><p className="text-xs text-slate-500">{form.resumeText?'Text extracted and available for matching.':'File name saved; add/paste resume text for browser-side prototype matching.'}</p></div></div>}<div><Label>Resume text</Label><textarea className="mt-2 w-full min-h-36 rounded-md border p-3 text-sm" value={form.resumeText||''} onChange={e=>set('resumeText',e.target.value)} placeholder="Paste resume text here for richer job-fit and skill recommendations."/></div></CardContent></Card></div>
 <div className="space-y-6"><Card><CardHeader><CardTitle>Live account summary</CardTitle></CardHeader><CardContent className="space-y-4"><div><p className="text-xs text-slate-500">Signed in as</p><p className="font-semibold">{user?.email}</p></div><div><p className="text-xs text-slate-500">Current</p><p className="font-semibold">{form.currentTitle||'Not set'}</p></div><div><p className="text-xs text-slate-500">Target</p><p className="font-semibold">{form.targetCareer||'Not set'}</p></div><div><p className="text-xs text-slate-500 mb-2">Skills</p><div className="flex flex-wrap gap-2">{String(form.skills||'').split(',').map((s:string)=>s.trim()).filter(Boolean).map(s=><Badge key={s}>{s}</Badge>)}</div></div></CardContent></Card><Card><CardHeader><CardTitle>What changes when you edit?</CardTitle></CardHeader><CardContent className="text-sm text-slate-600 dark:text-slate-300 space-y-2"><p>• Jobs are re-ranked against your target and current role.</p><p>• Skill gaps are calculated from target-role requirements.</p><p>• Learning options prioritize missing target skills.</p><p>• Community groups and posts follow your interests and career direction.</p><p>• AI job-fit analysis receives your current profile and resume context.</p></CardContent></Card></div></div></div>
}
